### PR TITLE
Update file renaming options page to show new examples section

### PR DESCRIPTION
**Pull request by rdswift**
### Summary

This is a…

- [x] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

The options screen for file renaming changed in https://github.com/metabrainz/picard/pull/1776

### Description of the Change

Update the image and description to match the revised option screen..

### Additional Action Required

None.

### CODE REVIEW

**Comment by phw** [comment]
Just a heads up that the details how this looks like might still change for a final 2.7 release.

**Comment by rdswift** [comment]
> Just a heads up that the details how this looks like might still change for a final 2.7 release.

Yup, but I thought I would get something started (in a new branch) so that I didn't forget about it.  We can pick away at it, updating as required if / when things change.

**Comment by phw** [comment]
@rdswift I cleaned up the next_version_2.7 branch and rebased it against master as it contained some code that was already in master and conflicted. But that means conflicts with this PR against next_version_2.7 need to be resolved also.

**Comment by rdswift** [comment]
It probably makes the most sense for me to cancel this PR and start a new one once the changes to the script editor are settled.

**Pull request closed without merging**
