### PR TITLE
Add some suggestions to the ToDo list.

### PR DESCRIPTION
**Pull request by Sophist-UK**
These are suggestions - using the PR approval process as a means of getting feedback and gaining consensus. So please feel free to disagree.

The biggest suggestion is the revamp of the multi-language approach. I am entirely unclear how the current Github structure facilitates translations into other languages. It appears to intend that this is done using Transifex, but I am really uncertain whether this is a good approach for this rather than manual translation due to its piecemeal approach - mainly because sentences or phrases in a text document (rather than message snippets in an application) may have a far greater contextual relevance to one another, but partly because (unlike app terminology) documentation phrases don't typically recur and so piecemeal translation is inefficient too.. But even if Transifex is used, I am unclear how e.g. a French version will be stored or generated, and how a french user using Picard with its French translation will get linked to the French version of this documentation. I think that the time to think this through and restructure is NOW.

P.S. I have only got about 1/2 way through the documentation - so likely that more suggestions will follow.

### CODE REVIEW

**Comment by phw** [comment]
Is this already on Transifex? 

Regarding the translation: Ideally the translation system used would segment the texts properly. You don't want to translate big lumps of texts. Also it helps with translation memory.

Most translation systems segment by sentence, as this is comparable easy to do automatically. But this can be too short and sometimes this leads you into trouble. If one sentence in the source would better be translated as multiple sentences in the target language that's easy to handle. But the oposite, having multiple source sentences better being translated as a single sentence, gives you trouble. Professional translation systems hence allow you to merge and split segments manually. Unfortunately I know of none online tool to allow this.

But the documentation usually has rather short paragraphs, so maybe segmenting by paragraphs would work more reliable.

Also the segments need to be presented always in context, otherwise you can't properly translate any longer text (this is where Transifex is not that great). Translation memory should be available as well, ideally with context aware matches.

We could look whether we can extract the texts in some portable format that can be handled by different tools. Unfortunately this is a bit messy. Maybe sticking with gettext .po format gives really most flexibility. Otherwise there is XLIFF in the translation world, but support varies widely and tooling is not too great.

**Comment by rdswift** [comment]
> Is this already on Transifex?

No.  I haven't yet placed it anywhere for translation, partly because it wasn't stable yet and partly because I wasn't sure if it would be allowed under the MetaBrainz account on Transifex since the repository isn't under MetaBrainz.  There have also been a LOT of complaints from translators about using Transifex and the suggestion was to consider Weblate as a possible alternative.  Weblate is open source, and you can self-host if you don't want to use their paid service.  I was considering setting up a local copy of the server for testing, but considering that I only speak one language I'm not sure I could properly evaluate it.  :grinning: 

> But the documentation usually has rather short paragraphs, so maybe segmenting by paragraphs would work more reliable.

I'm pretty sure that gettext has segmented each page (file) by paragraph.  Good for context, but still relatively short.  In addition, each page in a separate file keeps things in manageable chunks.

> We could look whether we can extract the texts in some portable format that can be handled by different tools. Unfortunately this is a bit messy. Maybe sticking with gettext .po format gives really most flexibility. Otherwise there is XLIFF in the translation world, but support varies widely and tooling is not too great.

The .pot files are also available (although I need to update them) for download and translation locally using something like Poedit.  They are under the `locale/gettext` directory.

**Comment by rdswift** [comment]
@Sophist-UK

> These are suggestions - using the PR approval process as a means of getting feedback and gaining consensus. So please feel free to disagree.

I have no major concerns with any of your suggestions, with the possible exception of the explanation of the data relationships in MusicBrainz.  If it's a simple diagram explaining basic concepts like release group versus release then it's not so bad, but for the most part Picard users are dealing with two entities: albums and tracks.  If this is intended as a way to nudge them toward MusicBrainz as new contributors, then I can see some value in it; however, in-depth understanding of the MusicBrainz data structure isn't really required to use Picard.

I did have to chuckle a bit when I read the comment about liking the way I referred to myself as an editor, especially since I just added a PR to remove that because we weren't listing any of the other contributors.  I really don't mind listing the contributors, but I'm always afraid I'm going to miss someone.

> The biggest suggestion is the revamp of the multi-language approach.

I added some comments about this in reply to @phw's comment.

> I am unclear how e.g. a French version will be stored or generated, and how a french user using Picard with its French translation will get linked to the French version of this documentation. I think that the time to think this through and restructure is NOW.

The translated .po files would be stored in a language-specific subdirectory of the `locale` directory, and sphinx automatically maps the translations when it builds the output files (e.g.: html, pdf or epub).  The script to publish the documentation builds each language set in the `conf.py` file and saves the (html) output in a language-specific directory.  Currently only the 'en' files are being produced.  In the root directory [https://picard-docs.musicbrainz.org/](https://picard-docs.musicbrainz.org/) the index.html file has some code to get the preferred language information from the user's browser and tries to find a match in the supported languages.  If one is found, it redirects to the appropriate language subdirectory, defaulting to 'en' if there is no match.  Once on the site, the language can be selected from the 'Options' link in the bottom left corner.

I actually started working on a translation to French (or was it German?) Using Google Translate (manually copying and pasting the text from the .pot files and copying the results to the corresponding .po file) but put it on hold because the documentation was still very much in flux.  I haven't gotten back to it.
 
> P.S. I have only got about 1/2 way through the documentation - so likely that more suggestions will follow.

I look forward to it.

One thing I was considering was to move each of the to-do items into a 'issue' to allow for better discussion and tracking of each item.  Any thoughts about that?

**Comment by Sophist-UK** [comment]
> If it's a simple diagram explaining basic concepts like release group versus release then it's not so bad, but for the most part Picard users are dealing with two entities: albums and tracks. If this is intended as a way to nudge them toward MusicBrainz as new contributors, then I can see some value in it; however, in-depth understanding of the MusicBrainz data structure isn't really required to use Picard.

I agree - in this section we should keep it simple, and GUI related - so Clusters / Albums (and special case NAT) / Tracks / Files.

In the tagging section we need the Release Groups / Releases / Tracks / Recordings / Works.

> I did have to chuckle a bit when I read the comment about liking the way I referred to myself as an editor, especially since I just added a PR to remove that because we weren't listing any of the other contributors. I really don't mind listing the contributors, but I'm always afraid I'm going to miss someone.

1. The purpose of having an editor is to have some leadership for each language version - leadership, not control.

2. You volunteered yourself - and qualified yourself for the role - for the English language version by creating it - but its not a job for life.

3. People can add themselves as contributors as part of their first PR.

> The translated .po files would be stored in a language-specific subdirectory of the `locale` directory, and sphinx automatically maps the translations when it builds the output files (e.g.: html, pdf or epub). The script to publish the documentation builds each language set in the `conf.py` file and saves the (html) output in a language-specific directory. Currently only the 'en' files are being produced. In the root directory https://picard-docs.musicbrainz.org/ the index.html file has some code to get the preferred language information from the user's browser and tries to find a match in the supported languages. If one is found, it redirects to the appropriate language subdirectory, defaulting to 'en' if there is no match. Once on the site, the language can be selected from the 'Options' link in the bottom left corner.

I really fear that a Transifex approach will result in other language versions that feel like they were translated by a child i.e. not coloquial.

> One thing I was considering was to move each of the to-do items into a 'issue' to allow for better discussion and tracking of each item. Any thoughts about that?

Not sure. The ToDo list is needed to provide an easy list of things for contributors to work on. I considered creating issues but in the end decided that it was easier and just as good to use a PR changing the ToDo list as a way of discussing the ideas I had. BUT... with hindsight, perhaps I should have created an issue for the translation question as this is going to need some extensive discussion - and the ToDo list can have a link to the issue which discussed it and reached a conclusion.

**Comment by rdswift** [comment]
I just created a [Google Doc](https://docs.google.com/document/d/1vy9Ncqi57uS5AU8fhL8blV_PtmNiTf4EQyJ-lOKrQA8/edit?usp=sharing) with my thoughts regarding project roles & responsibilities, and workflow.  Part of that is a new `publish` branch to allow batching changes and allowing time for translation.  If I set it up correctly, you should be able to make changes and comments directly in the document.  Once there is some sort of consensus, I'm thinking that the information should be posted as wiki pages for the project.  Comments welcome.

**Comment by Sophist-UK** [comment]
@rdswift Bob - Thank you indeed for putting the effort into creating the google doc. Here are my comments:

1. I still think that use of Transifex (or even .pot) files is overkill and a ***BAD IDEA***!! If we want to create a Klingon version of the document, we could manually put each page through the Google English to Klingon translator, and create a new Klingon first-cut version of the page. People who are fluent in Klingon - which I guess would normally be ... um ... actual Klingons ;-) - could then tweak the text to be more coloquial and correct any Google AI stupidities. (Example: Google's Portuguese is Brazilian Portuguese - so the Portugal Portuguese translation will need correcting by a human.)

When a PR is merged for the English version, the Klingon Translation Lead is responsible for tracking this until an equivalent translation is applied to the Klingon page through an equivalent Klingon PR. They could do it themselves, or someone else could do it. And IMO that is the purpose of the Translation Lead - to ensure that English changes make it into their language version.

2. Yes - we need Translators who can produce coloquial versions, and we need Translation Reviewers so that we have quality control. But in practice, we could probably do this with two people, the Translation Lead and one other who between them share the Translator / Translation Review roles, though there is no problem with having more people for a language. The key rule is that whoever submits the translation, someone else has to review and approve it. This doesn't seem to be a problem with Picard PRs and I cannot see why it should be a problem with doc translations.

3. In general I am in agreement with the Workflow, however I think we should keep the basic publish simple and update the web site every time a PR is merged. We can then take snapshots of web, PDF and ePub whenever we create a formal Picard release for historical purposes. If we wanted to we could then have Picard add the release version to the URL (as well as the locale) in order to link to the best page for the version / language they are using. If we wanted to (and I am not saying that we should do this - just punting it as an idea) we could even include a snapshot of the web site and / or PDF and / or ePub in the packaged release of Picard. Aside from releases (where we would want to include checking that the documentation is release ready as well as Picard itself), I really don't see any issues with e.g. English being slightly ahead of Klingon for a few days.

**Pull request merged**
