### PR TITLE
Tagger Script syntax highlight

### PR DESCRIPTION
**Pull request by phw**
### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change

Provide syntax highlighting for Picard Tagger Script in code examples.

### Description of the Change

- Add a Sphinx extension that registers a custom Pygments lexer for the Tagger Script syntax
- Add a stylesheet to highlight taggerscript with the same colors as Picard does
- Mark all code blocks explicitly for taggerscript

### CODE REVIEW

**Comment by phw** [comment]
Need to check how to make the RST linting happy.

**Comment by rdswift** [comment]
> Need to check how to make the RST linting happy.

I just pushed a code change to take care of that.  Hope you don't mind.

**Comment by phw** [comment]
Thanks a lot for fixing this, much appreciated.

**Comment by phw** [comment]
I fixed the formatting for comments. Just to give a feeling how this looks like for a more complex script:

grafik

**Review by rdswift — APPROVED** [review]
This looks great, and works well in the PDF output as well.  Thanks for this.

I need to fix a couple of the tests in `setup.py` to properly handle the wildcard in the `PYTHON_FILES_TO_CHECK` list, but I'll do that in a separate commit because there are some other things that I want to change as well.

**Pull request merged**
